---
# Install custom system packages
# The following will be installed by hand
# but dependencies may be installed here
# - Ansible
# - Emacs

- hosts: all
  tasks:

    - name: Add tarsnap packaging key
      apt_key:
        url: https://pkg.tarsnap.com/tarsnap-deb-packaging-key.asc
        state: present

    - name: Add tarsnap apt repository
      apt_repository:
        repo: "deb http://pkg.tarsnap.com/deb/{{ ansible_distribution_release }} ./"
        state: present

    - name: Add brave browser packaging key
      apt_key:
        url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
        state: present

    - name: Add brave browser apt repository
      apt_repository:
        repo: "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"
        state: present

    - name: Add Vagrant packaging key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: Add Vagrant apt repository
      apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 21600

    - name: Install Basic Packages
      apt:
        state: latest
        autoremove: yes
        name:
          - vagrant
          - vlc
          - git
          - git-lfs
          - python3-pip
          - nfs-kernel-server
          - traceroute
          - cheese
          - libedit-dev
          - nethogs
          - redshift
          - redshift-gtk
          - xclip
          - cryptsetup
          - graphviz
          - whois
          - valgrind
          - rkhunter
          - tiger
          - gimp
          - macchanger
          - ngrep
          - lxc
          - wireshark
          - python-dev
          - python3-dev
          - calibre
          - android-tools-adb
          - brave-browser
          - unrar
          - gparted
          - virtualbox
          - build-essential
          - curl
          - tarsnap
          - kdenlive
          - blender
          - okular
          - swaks

    - name: Install general Python deps
      pip:
        state: latest
        executable: pip3
        name:
          - python-language-server
          - virtualenv
          - flake8
          - coverage
          - nose
          - requests

    - name: Append user to virtualbox group
      user:
        name: krm
        groups: vboxusers
        append: yes

    - name: Install nvm
      become_user: krm
      shell: >
        wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      args:
        creates: "/home/krm/.nvm/nvm.sh"
