---
# Install custom system packages
# The following will be installed by hand
# - Ansible
# - Emacs

- hosts: all
  tasks:

    - name: Add opentofu packaging key
      ansible.builtin.get_url:
        url: https://packages.opentofu.org/opentofu/tofu/gpgkey
        dest: /etc/apt/trusted.gpg.d/opentofu.asc

    - name: Add opentofu repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/trusted.gpg.d/opentofu.asc] https://packages.opentofu.org/opentofu/tofu/any/ any main"
        state: present

    - name: Add tarsnap packaging key
      apt_key:
        url: https://pkg.tarsnap.com/tarsnap-deb-packaging-key.asc
        state: present

    - name: Add tarsnap apt repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/tarsnap-archive-keyring.gpg] http://pkg.tarsnap.com/deb/{{ ansible_distribution_release }} ./"
        state: present

    - name: Add brave browser packaging key
      apt_key:
        url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
        state: present

    - name: Add brave browser apt repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"
        state: present

    - name: Add Vagrant packaging key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: Add Vagrant apt repository
      apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present

    - name: Add dbeaver packaging key
      apt_key:
        url: https://dbeaver.io/debs/dbeaver.gpg.key
        keyring: /usr/share/keyrings/dbeaver.gpg.key
        state: present

    - name: Add dbeaver apt repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/dbeaver.gpg.key] https://dbeaver.io/debs/dbeaver-ce /"
        state: present

    - name: Add obs studio packaging key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: BC7345F522079769F5BBE987EFC71127F425E228

    - name: Add obs studio repository
      apt_repository:
        repo: "deb https://ppa.launchpadcontent.net/obsproject/obs-studio/ubuntu {{ ansible_distribution_release }} main"
        state: present

    - name: Add deadsnakes team packaging key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: F23C5A6CF475977595C89F51BA6932366A755776

    - name: Add deadsnakes team repository 
      apt_repository:
        repo: "deb https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu {{ ansible_distribution_release }} main"
        state: present

    - name: Add go-ethereum packaging key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 2A518C819BE37D2C2031944D1C52189C923F6CA9

    - name: Add go-ethereum team repository
      apt_repository:
        repo: "deb https://ppa.launchpadcontent.net/ethereum/ethereum/ubuntu {{ ansible_distribution_release }} main"
        state: present

    - name: Install extrepo
      apt:
        state: latest
        name: extrepo

    - name: Enable librewolf
      shell: extrepo enable librewolf

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 21600
        upgrade: yes

    - name: Install Basic Packages
      apt:
        state: present
        autoremove: yes
        name:
          - vagrant
          - vlc
          - git
          - git-lfs
          - python3-pip
          - nfs-kernel-server
          - traceroute
          - cheese
          - libedit-dev
          - nethogs
          - redshift
          - redshift-gtk
          - xclip
          - cryptsetup
          - graphviz
          - whois
          - valgrind
          - rkhunter
          - tiger
          - gimp
          - macchanger
          - ngrep
          - lxc
          - wireshark
          - python3-dev
          - python3-setuptools
          - calibre
          - android-tools-adb
          - brave-browser
          - unrar
          - gparted
          - virtualbox
          - build-essential
          - python3-venv
          - curl
          - tarsnap
          - kdenlive
          - breeze
          - blender
          - okular
          - swaks
          - k3b
          - obs-studio
          - python3.9
          - python3.9-dev
          - python3.9-venv
          - python3.10
          - python3.10-dev
          - python3.10-venv
          - python3.11
          - python3.11-dev
          - python3.11-venv
          - python3.12
          - python3.12-dev
          - python3.12-venv
          - texlive-latex-base
          - texlive-latex-extra
          - texlive-xetex
          - texlive-fonts-recommended
          - texlive-plain-generic
          - vlc-plugin-fluidsynth
          - ethereum
          - docker.io
          - docker-compose-v2
          - docker-buildx
          - kcachegrind
          - qpdf
          - libpq-dev
          - dbeaver-ce
          - pencil2d
          - tofu
          - pandoc
          - librewolf

    - name: Install python packages via pip
      pip:
        state: latest
        executable: pip3
        name:
          - virtualenv

    - name: Add user to additional groups
      user:
        name: krm
        groups:
          - vboxusers
          - docker
        append: yes

    - name: Install nvm
      become_user: krm
      shell: >
        wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      args:
        creates: "/home/krm/.nvm/nvm.sh"
