---
# Install custom system packages
# The following will be installed by hand
# but dependencies may be installed here
# - Ansible
# - Emacs
# - Vagrant

- hosts: all
  tasks:

    - name: Add tarsnap packaging key
      apt_key:
        url: https://pkg.tarsnap.com/tarsnap-deb-packaging-key.asc
        state: present

    - name: Add tarsnap repository
      apt_repository:
        repo: "deb http://pkg.tarsnap.com/deb/{{ ansible_distribution_release }} ./"
        state: present

    - name: Add brave browser packaging key
      apt_key:
        url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
        state: present

    - name: Add brave browser repository
      apt_repository:
        repo: "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 21600

    - name: Install Basic Packages
      apt:
        state: latest
        autoremove: yes
        name:
          - vlc
          - git
          - python-pip
          - nfs-kernel-server
          - traceroute
          - cheese
          - libedit-dev
          - nethogs
          - redshift
          - redshift-gtk
          - xclip
          - cryptsetup
          - graphviz
          - whois
          - valgrind
          - rkhunter
          - tiger
          - gimp
          - macchanger
          - ngrep
          - lxc
          - wireshark
          - python-dev
          - python3-dev
          - calibre
          - android-tools-adb
          - chromium-browser
          - brave-browser
          - unrar
          - gparted
          - virtualbox
          - build-essential
          - curl
          - tarsnap
          - kdenlive
          - blender

    - name: Install general Python deps
      pip:
        state: latest
        name:
          - virtualenv
          - flake8
          - jedi
          - coverage
          - nose
          - requests

    - name: Append user to virtualbox group
      user:
        name: krm
        groups: vboxusers
        append: yes
